[versions]
# libraries
annotations = "24.1.0"
jackson = "2.20.1"
flexmark = "0.64.8"

# plugins
kotlin = "2.2.20"
changelog = "2.2.1"
gradleIntelliJPluginVersion = "2.10.5"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
jackson = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
flexmark = { group = "com.vladsch.flexmark", name = "flexmark-all", version.ref = "flexmark" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPluginVersion" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
